########################################################################
# Makefile                                                             #
#                                                                      #
# For irimage and flimage					       #
#                                                                      #
########################################################################
#                                                                      #
#		THE CHARA ARRAY					       #
#     Center for High Angular Resolution Astronomy                     #
# Georgia State University, Atlanta GA 30303-3083, U.S.A.              #
#                                                                      #
#                                                                      #
# Telephone: 1-626-796-5405                                            #
# Fax      : 1-626-796-6717                                            #
# email    : theo@chara.gsu.edu                                        #
# WWW      : http:www.chara.gsu.edu 		                       #
#                                                                      #
# (C) This source code and its associated executable                   #
# program(s) are copyright.                                            #
#                                                                      #
########################################################################
#                                                                      #
# Author : Theo ten Brummelaar                                         #
# Date   : JAN 1998      					       #
########################################################################

#
# The targets
#

all: 
	./Build all

clean:
	./Build clean

install: 
	./Build install

uninstall:
	./Build uninstall
